.\" Manpage for jsh.
.TH JSH 1 "11 October 2014" "1.0" "jsh man page" .\" TODO fill in
.SH NAME
jsh (jo-shell) \- A proof-of-concept UNIX shell implementation in C
.SH SYNOPSIS
\fBjsh\fP [options]
.SH DESCRIPTION
\fBjsh\fP is a UNIX command interpreter (shell) that executes commands read from the standard input or from a file. Jsh implements a subset of the \fBsh\fP language grammar and is intended to be POSIX-conformant.

\fBjsh\fP is written 'just for fun' and is not intented to be a complete replacement for standard UNIX shells such as bash. Jsh is free software and you are welcome to collaborate on the github page (https://github.com/jovanbulck/jo-shell) or to redistribute jsh under the conditions of the GNU General Public License.
.SH OPTIONS
\fBjsh\fP supports any combination of the following options:
.TP
\fB\-h, \--help\fP
display an informative help message and exit
.TP
\fB\-d, \--debug\fP
turn printing of debug messages on
.TP
\fB\-n, \--nodebug\fP
turn printing of debug messages off
.TP
\fB\-c, \--color\fP
turn coloring of jsh output messages on
.TP
\fB\-o, \--nocolor\fP
turn coloring of jsh output messages off
.TP
\fB\-d, \--norc\fP
disable autoloading of the ~/.jshrc file
.TP
\fB\-l, \--license\fP
display licence information and exit
.SH FILES
.TP
\fI~/.jshrc\fP
file containing commands to be executed at login
.TP
\fI~/.jsh_login\fP
file containing the welcome message auto printed at login of an interactive session
.TP
\fI~/.jsh_history\fP
file containing the command history auto loaded and saved at login/logout
.SH THE JSH WIKI
\fBjsh\fP has a wiki (https://github.com/jovanbulck/jo-shell/wiki) where you can find up-to-date information and installation instructions for various platforms.
.SH BUGS REPORTS
If you find a bug in \fBjsh\fP, you should report it on the github page (https://github.com/jovanbulck/jo-shell). Note you can always find the latest version here. Please check first whether the bug appears in the latest version of jsh.
.SH KNOWN BUGS
One cannot overwrite the binary of \fBjsh\fP from within an executing \fBjsh\fP session.

Job control is not yet implemented; pressing ^Z will suspend the \fBjsh\fP shell.
.SH AUTHOR
\fBjsh\fP was orginally written by Jo Van Bulck <jo.vanbulck@student.kuleuven.be>. Other contributers are listed on the github project (https://github.com/jovanbulck/jo-shell/graphs/contributors).
.SH LICENSE
\fBjsh\fP is free software, licensed under the GNU General Public License (https://gnu.org/licenses/gpl.html). Execute \fBjsh --license\fP for more information.
.SH SEE ALSO
\fIsh(1)\fR, \fIbash(1)\fR, \fIreadline(1)\fR.
