UNAME_S                 = $(shell uname -s)
JSH_INSTALL_DIR         = /usr/local/bin
MANPAGE_INSTALL_DIR     = /usr/local/man/man1

ifeq ($(UNAME_S), Darwin) # Add library folder for Mac OS X readline (installed with homebrew)
	LINK := gcc -g jsh-common.o jsh.o alias.o -o jsh -L/usr/local/lib/ -lreadline
else
	LINK := gcc -g jsh-common.o jsh.o alias.o -o jsh -lreadline -lncurses
endif

all: jsh-common alias jsh link
	@echo "-------- Compiling all done --------"

jsh-common: jsh-common.c jsh-common.h
	gcc -g -c jsh-common.c -o jsh-common.o
alias: alias.c alias.h jsh-common.h
	gcc -g -c alias.c -o alias.o
jsh: jsh-parse.c jsh.c jsh-common.h
	gcc -g -c jsh.c -o jsh.o
link: jsh-common.o jsh.o alias.o
	$(LINK)

.PHONY: install
install: all
	@echo "installing jsh executable in directory $(JSH_INSTALL_DIR)..."
	@test -d $(JSH_INSTALL_DIR) || (mkdir $(JSH_INSTALL_DIR) && echo "created directory $(JSH_INSTALL_DIR)")
	@install -m 0755 jsh $(JSH_INSTALL_DIR);
	
	@echo "installing the manpage in directory $(MANPAGE_INSTALL_DIR)..."
	@test -d $(MANPAGE_INSTALL_DIR) || (mkdir $(MANPAGE_INSTALL_DIR) && echo "created directory $(MANPAGE_INSTALL_DIR)")
	@install -m 0644 jsh.1 $(MANPAGE_INSTALL_DIR);
	@echo "updating man-db..."
	@mandb --quiet
	@echo "-------- Installation all done --------"

.PHONY: clean
clean:
	@rm -f jsh-common.o alias.o jsh.o jsh
	
.PHONY : help
help:
	@echo "The following are the valid targets for this Makefile:"
	@echo "... all     -- (the default if no target is provided); compiles the jo-shell to the 'jsh' binary in the current directory"
	@echo "... clean   -- removes all object files generated by the build process"
	@echo "... install -- installs the jsh binary to $(JSH_INSTALL_DIR) and the jsh man page to $(MANPAGE_INSTALL_DIR)"

