JSH_INSTALL_DIR         = /usr/local/bin
MANPAGE_INSTALL_DIR     = /usr/local/share/man/man1

CC                      = gcc
CFLAGS                  = -g
LIBS                    = -lreadline
LN                      = $(CC) $(CFLAGS) jsh-common.o jsh.o alias.o -o jsh $(LIBS)

ECHO_LIBS               = echo "Linking jsh with the following libraries: $(LIBS) "

UNAME_S                 = $(shell uname -s)

ifeq ($(UNAME_S), Darwin)
	LINK = @$(LN) -L/usr/local/lib/ # Add library folder for Mac OS X readline (installed with homebrew)
else # try to link jsh with the readline library (and curses or termcap if needed)
	LINK = @(($(ECHO_LIBS)); ($(LN)) || (($(ECHO_LIBS) "lncurses"); $(LN) -lncurses) || \
	(($(ECHO_LIBS) "termcap"); $(LN) -termcap) || (echo "Failed linking jsh: all known fallback libraries were tried"))
endif

all: jsh-common alias jsh link
	@echo "-------- Compiling all done --------"

jsh-common: jsh-common.c jsh-common.h
	$(CC) $(CFLAGS) -c jsh-common.c -o jsh-common.o
alias: alias.c alias.h jsh-common.h
	$(CC) $(CFLAGS) -c alias.c -o alias.o
jsh: jsh-parse.c jsh.c jsh-common.h
	$(CC) $(CFLAGS) -c jsh.c -o jsh.o
link: jsh-common.o jsh.o alias.o
	$(LINK)

.PHONY: install
install: all
	@echo "installing jsh executable in directory $(JSH_INSTALL_DIR)..."
	@test -d $(JSH_INSTALL_DIR) || (mkdir -p $(JSH_INSTALL_DIR) && echo "created directory $(JSH_INSTALL_DIR)")
	@install -m 0755 jsh $(JSH_INSTALL_DIR);
	
	@echo "installing the manpage in directory $(MANPAGE_INSTALL_DIR)..."
	@test -d $(MANPAGE_INSTALL_DIR) || (mkdir -p $(MANPAGE_INSTALL_DIR) && echo "created directory $(MANPAGE_INSTALL_DIR)")
	@install -m 0644 jsh.1 $(MANPAGE_INSTALL_DIR);
ifneq ($(UNAME_S), Darwin) # Man-DB update is not necessary on Mac
	@echo "updating man-db..."
	@mandb --quiet
endif
	@echo "-------- Installation all done --------"

.PHONY: clean
clean:
	@rm -f jsh-common.o alias.o jsh.o jsh
	
.PHONY : help
help:
	@echo "The following are the valid targets for this Makefile:"
	@echo "... all     -- (the default if no target is provided); compiles the jo-shell to the 'jsh' binary in the current directory"
	@echo "... clean   -- removes all object files generated by the build process"
	@echo "... install -- installs the jsh binary to $(JSH_INSTALL_DIR) and the jsh man page to $(MANPAGE_INSTALL_DIR)"

